// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odrbgrruvvqfphyafoxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kcmJncnJ1dnZxZnBoeWFmb3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzgzNjksImV4cCI6MjA2OTc1NDM2OX0.93o4QsWm83DI7nmrWNB69Ovk23oPMmdEcQMgbxMLv4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});